# fly.toml app configuration file generated for frost-playground on 2025-05-03T18:10:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frost-playground'
primary_region = 'fra'

[build]
  [build.args]
    GO_VERSION = '1.24.0'

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
